version: "3"
services:
  db:
    image: mysql:8.0.28-oracle
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ecommerce
    ports:
      - 3306:3306
